name: material_paper_colors
version: 0.0.1
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: material design paper color palette maps
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_core
environment:
  sdk: '>=0.8.10+6 <2.0.0'