name: material_paper_colors
version: 0.0.2
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: access material design paper color palette via map object and color range
homepage: https://github.com/HannesRammer/material_paper_colors
environment:
  sdk: '>=0.8.10+6 <2.0.0'
